version: "3.8"
services: 
  coordinator:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido
    network_mode: "host"

  worker1:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    network_mode: "host"      

  worker2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    network_mode: "host"

  worker3:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    network_mode: "host"

  worker4: 
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ./algoritmo_distribuido worker
    network_mode: "host"
